services:
  portfolio:
    image: portfolio:latest
    container_name: portfolio
    restart: unless-stopped
    env_file:
      - .env.local
      - .env.production

networks:
  default:
    name: swag
    external: true
