services:
  portfolio:
    image: portfolio:latest
    container_name: portfolio
    restart: unless-stopped
    env_file:
      - .env.local
      - .env.production
  mongo:
    image: mongo@latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/data/db
  mongo-express:
    image: mongo-express@latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_EXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_ROOT_USER}:${DB_ROOT_PASSWORD}@mongo:27017/

networks:
  default:
    name: swag
    external: true
