/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 capsule.glb --transform --t 
Files: capsule.glb [8.51KB] > /Users/lefan/Programming/portfolio/public/capsule-transformed.glb [2.54KB] (70%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Capsule: THREE.Mesh;
  };
  materials: {};
  // animations: GLTFAction[];
};

export function CapsuleModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/capsule-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <pointLight intensity={500} decay={2} position={[10, 10, 10]} />
      <mesh
        geometry={nodes.Capsule.geometry}
        material={nodes.Capsule.material}
        position={[-3.007, 0.586, 0]}
      />
    </group>
  );
}

useGLTF.preload("/capsule-transformed.glb");
