/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 Display.glb --transform --t --k 
Files: Display.glb [5.05KB] > /Users/lefan/Programming/portfolio/public/Display-transformed.glb [2.62KB] (48%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Box: THREE.Mesh
    Box_1: THREE.Mesh
    Plane: THREE.Mesh
  }
  materials: {}
  // animations: GLTFAction[]
}

export function DisplayModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Display-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Box" geometry={nodes.Box.geometry} material={nodes.Box.material} position={[0, 2, 0]} />
      <mesh name="Box_1" geometry={nodes.Box_1.geometry} material={nodes.Box_1.material} position={[0, 2, -0.02]} />
      <mesh name="Plane" geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[0, 2, 0.02]} />
    </group>
  )
}

useGLTF.preload('/Display-transformed.glb')
